source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ZM_Networking_Example', :exclusive => true do
  pod 'ZM_Networking', :path => '../'
end

target 'ZM_Networking_Tests', :exclusive => true do
  pod 'ZM_Networking', :path => '../'

  
end
